function docs = temptable2stimulusparameters(S)
    % TEMPTABLE2STIMULUSPARAMETERS - Create stimulus parameter documents from a temperature table.
    %
    % DOCS = TEMPTABLE2STIMULUSPARAMETERS(S)
    %
    % Creates 'stimulus_parameter' NDI documents based on the analysis of
    % temperature data stored in 'temptable.mat'. This function links temperature
    % command values to stimulus epochs.
    %
    % The function loads 'temptable.mat', which is generated by
    % `ndi.setup.conv.marder.bath.preptemptable`. For each epoch of each 'stimulator'
    % probe, it finds the corresponding temperature information and creates
    % NDI documents that describe the temperature stimulus parameters
    % (e.g., 'Command temperature constant', 'Command temperature start').
    %
    % If an epoch does not have a direct temperature measurement, it uses the
    % measurement from the most recent preceding epoch that did.
    %
    % INPUTS:
    %   S: (ndi.session) The NDI session object.
    %
    % OUTPUTS:
    %   docs: (cell array of ndi.document) A cell array of the newly created
    %         'stimulus_parameter' documents. Note: These documents are NOT
    %         automatically added to the database.
    %
    % REQUIRED FILES:
    %   - [session_path]/temptable.mat: A MAT-file containing the 'temptable'
    %     variable, generated by `ndi.setup.conv.marder.bath.preptemptable`.
    %
    % EXAMPLE:
    %   % First, generate the temperature table
    %   ndi.setup.conv.marder.bath.preptemptable(S);
    %   % Then, create the stimulus parameter documents
    %   stim_docs = ndi.setup.conv.marder.bath.temptable2stimulusparameters(S);
    %   S.database_add(stim_docs); % Add the new documents to the database
    %
    % See also: ndi.setup.conv.marder.bath.preptemptable, ndi.document

    arguments
        S (1,1) ndi.session 
    end

    dirname = S.getpath();

    t = load([dirname filesep 'temptable.mat'],'-mat');

    temptable = t.temptable;

    stim = S.getprobes('type','stimulator');

    et = stim{1}.epochtable();

    item_const = ndi.database.fun.ndicloud_ontology_lookup('Name','Command temperature constant');
    item_start = ndi.database.fun.ndicloud_ontology_lookup('Name','Command temperature start');
    item_end = ndi.database.fun.ndicloud_ontology_lookup('Name','Command temperature end');

    const_o = ['NDIC:' int2str(item_const.Identifier)];
    temp_start = ['NDIC:' int2str(item_start.Identifier)];
    temp_end = ['NDIC:' int2str(item_end.Identifier)];

    last_match = [];

    docs = {};

    for i=1:numel(et)
        ind = find(strcmp(et(i).epoch_id,temptable.("epoch_id")));
        if ~isempty(ind)
            last_match = temptable(ind,:);
        end
        if isempty(last_match), continue; end

        for p=1:numel(stim)
            if strcmp(last_match.type,"constant")
                eid.epochid = et(i).epoch_id;
                d_struct.ontology_name = const_o;
                d_struct.name = 'Command temperature constant';
                d_struct.value = last_match.temp{1};
                d_here = ndi.document('stimulus_parameter','stimulus_parameter',d_struct,...
                    'epochid',eid) + S.newdocument();
                d_here = d_here.set_dependency_value('stimulus_element_id',stim{p}.id());
                docs{end+1} = d_here;
            end
            if strcmp(last_match.type,"change")
                eid.epochid = et(i).epoch_id;
                d_struct1.ontology_name = temp_start;
                d_struct1.name = 'starting temperature';
                d_struct1.value = last_match.temp{1}(1);
                d_here = ndi.document('stimulus_parameter','stimulus_parameter',d_struct1,...
                    'epochid',eid) + S.newdocument();
                d_here = d_here.set_dependency_value('stimulus_element_id',stim{p}.id());
                docs{end+1} = d_here;
                d_struct2.ontology_name = temp_end;
                d_struct2.name = 'ending temperature';
                d_struct2.value = last_match.temp{1}(2);
                d_here = ndi.document('stimulus_parameter','stimulus_parameter',d_struct2,...
                    'epochid',eid) + S.newdocument();
                d_here = d_here.set_dependency_value('stimulus_element_id',stim{p}.id());
                docs{end+1} = d_here;
            end
        end
    end
